# Generated by Django 5.2.8 on 2025-12-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0003_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yields', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preparationTimeInMinutes', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recipes', to='sweet_princing_v2_recipe.product')),
            ],
        ),
    ]
