# Generated by Django 5.2.8 on 2025-12-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0006_alter_recipe_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='recipe', to='sweet_princing_v2_recipe.product'),
        ),
    ]
