# Generated by Django 4.2.27 on 2025-12-08 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0011_recipeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitOfMeasure', models.SmallIntegerField(choices=[(1, 'Quilograma'), (2, 'Grama'), (3, 'Miligrama'), (4, 'Litro'), (5, 'Mililitro'), (6, 'Colher de chá'), (7, 'Colher de sopa'), (8, 'Colher de sobremesa'), (9, 'Xícara'), (10, 'Unidade'), (11, 'Pitada'), (12, 'Copo americano'), (13, 'Concha')], default=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sweet_princing_v2_recipe.ingredient')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet_princing_v2_recipe.purchase')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
