# Generated by Django 4.2.27 on 2025-12-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0013_ingredient_user_product_user_purchase_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unitOfMeasure',
            field=models.SmallIntegerField(choices=[(1, 'Miligrama'), (2, 'Mililitro')], default=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sweet_princing_v2_recipe.product'),
        ),
    ]
