INSERT INTO sweet_princing_v2_recipe_supplier (name, user_id) VALUES
('Atacadão', 1),
('Assaí Atacadista', 1),
('Carrefour', 1),
('Havan', 1),
('Angeloni', 1),
('Cassol Centerlar', 1),
('Brasil Atacado', 1),
('Supermercado Giassi', 1),
('Makro Atacadista', 1),
('Mercado Livre', 1),
('Loja de Embalagens Central', 1),
('Confeiteiro Store', 1),
('Distribuidora de Alimentos Sul', 1),
('Açougue Bom Corte', 1),
('Casa do Confeiteiro', 1),
('Chocolates Gourmet Brasil', 1),
('Empório Sabores', 1),
('Flor de Açúcar Distribuidora', 1),
('Laticínios Serra Alta', 1),
('Sabor & Arte Atacado', 1);
